// s00-title: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { gothicShot, lightning } from '/song/lib/shots.js';
import { linesIn } from '/song/lib/type.js';
export const kind = 'shader';
export default (P) => { const lines = linesIn(P); return gothicShot(P, { name: 's00-title', cam: (p, t) => ({ pos: [0.8, 1.0 + 0.6 * p, 2.0 + 3.0 * p], target: [-0.6, 3.0 + 4.0 * p, 30], fov: 50 }), uniforms: { uVotive: [-3.1, 0.0, 9.2] }, update: (t, u) => { u.uVotiveOn.value = t > 0.45 ? 1 : 0; u.uMoonCol.value.set(...[4.6, 5.4, 7.2].map((v) => v * Math.min(1, Math.max(0, (t - 1.0) / 6.0)))); }, exposure: 2.6, post: (t) => ({ fade: 0 }) }); };
