// s00-title: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { lyricModule, verse, single, shout, note, outFade, ease, clamp01, setLine, lyrics } from '/song/lib/type.js';
export default lyricModule((ctx, t, P, lines) => {
  const k = ease.out3(clamp01((t - 2.2) / 1.6)) * outFade(t, P.to - 0.6, P.to);
  if (k <= 0) return;
  note(ctx, 'THE', 1920, 860, { px: 70, align: 'center', alpha: 0.85 * k, track: 0.6 });
  shout(ctx, [{ w: 'FAITH', start: 2.4 }, ], t, { cx: 1920, y: 1240, big: 360, alpha: k });
  note(ctx, 'OF THE APOSTLES', 1920, 1420, { px: 90, align: 'center', alpha: 0.9 * k, track: 0.45, color: '255, 172, 72' });
});
