// s01-doors: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { spilledShot } from '/song/lib/shots.js';
import { linesIn } from '/song/lib/type.js';
export const kind = 'three';
export default (P) => { const lines = linesIn(P); return spilledShot(P, { name: 's01-doors', cam: (p, t) => ({ pos: [0.3, 1.6, -22 + 9 * p], target: [0, 5.5, 10], fov: 52 }), fillK: (t) => 0.25 + 0.75 * Math.min(1, Math.max(0, (t - 12) / 9)) }); };
