// s03-lamp: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { gothicShot, lightning } from '/song/lib/shots.js';
import { linesIn, ease } from '/song/lib/type.js';
export const kind = 'shader';
export default (P) => { const lines = linesIn(P); return gothicShot(P, { name: 's03-lamp', cam: (p, t) => ({ pos: [-2.2 + 0.25 * p, 1.05, 7.6 + 0.3 * p], target: [-3.1, 0.75, 9.3], fov: 34, focus: 1.9 }), uniforms: { uVotive: [-3.1, 0.0, 9.2], uAperG: 0.03 } }); };
