// s07-kings: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { gothicShot, lightning } from '/song/lib/shots.js';
import { linesIn } from '/song/lib/type.js';
export const kind = 'shader';
export default (P) => { const lines = linesIn(P); return gothicShot(P, { name: 's07-kings', cam: (p, t) => ({ pos: [1.2, 1.1 + 0.5 * p, -2.0 + 4.5 * p], target: [-0.4, 6.5 + 0.8 * p, 30.0], fov: 52 }), uniforms: { uVotive: [-3.1, 0.0, 9.2] } }); };
