// s09-font: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { spilledShot } from '/song/lib/shots.js';
import { linesIn } from '/song/lib/type.js';
export const kind = 'three';
export default (P) => { const lines = linesIn(P); return spilledShot(P, { name: 's09-font', cam: (p, t) => ({ pos: [0, 1.8 + 1.0 * p, 0.01], target: [0.0, 30, 0.02], fov: 70, roll: 0.5 * p }) }); };
