// s09-font: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { lyricModule, verse, single, shout, note, outFade, ease, clamp01, setLine, lyrics } from '/song/lib/type.js';
export default lyricModule((ctx, t, P, lines) => {
  verse(ctx, t, P, lines, { x: 1920, y: 1180, px: 280, align: 'center', groups: [1, 1, 1, 2], gap: 1.2 });
});
