// s11-fathers: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { spilledShot } from '/song/lib/shots.js';
import { linesIn } from '/song/lib/type.js';
export const kind = 'three';
export default (P) => { const lines = linesIn(P); return spilledShot(P, { name: 's11-fathers', cam: (p, t) => ({ pos: [-2.5, 1.6 + 1.5 * p, -12 + 2 * p], target: [1.5, 7 + 2 * p, 10], fov: 50 }) }); };
