// s12-nave: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { spilledShot } from '/song/lib/shots.js';
import { linesIn } from '/song/lib/type.js';
export const kind = 'three';
export default (P) => { const lines = linesIn(P); return spilledShot(P, { name: 's12-nave', cam: (p, t) => ({ pos: [-9 + 4 * p, 1.6, -9 + 9 * p], target: [-2 + 4 * p, 5, 12], fov: 56 }) }); };
