// s13-holy: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { spilledShot } from '/song/lib/shots.js';
import { linesIn } from '/song/lib/type.js';
export const kind = 'three';
export default (P) => { const lines = linesIn(P); return spilledShot(P, { name: 's13-holy', cam: (p, t) => ({ pos: [0, 2.0, 0.01], target: [0.0, 30, 0.02], fov: 74, roll: 1.2 * p }), fill: 5.5 }); };
