// s14-mighty: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { lyricModule, verse, single, shout, note, outFade, ease, clamp01, setLine, lyrics } from '/song/lib/type.js';
export default lyricModule((ctx, t, P, lines) => {
  verse(ctx, t, P, lines.slice(0, 3), { x: 260, y: 860, px: 210, align: 'left', group: 3, gap: 1.3 });
  verse(ctx, t, P, lines.slice(3), { x: 1920, y: 1880, px: 240, align: 'center', group: 1 });
});
