// s14-mighty: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { spilledShot } from '/song/lib/shots.js';
import { linesIn } from '/song/lib/type.js';
export const kind = 'three';
export default (P) => { const lines = linesIn(P); return spilledShot(P, { name: 's14-mighty', cam: (p, t) => ({ pos: [3.0 * Math.cos(2.2 + 0.8 * p), 2.4, 6.5 + 3.0 * Math.sin(2.2 + 0.8 * p)], target: [0, 4.5, 8], fov: 50 }) }); };
