// s16-thrones: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { gothicShot, lightning } from '/song/lib/shots.js';
import { linesIn, ease } from '/song/lib/type.js';
export const kind = 'shader';
export default (P) => { const lines = linesIn(P); return gothicShot(P, { name: 's16-thrones', cam: (p, t) => ({ pos: [0.0, 11.0 - 2 * p, 4 + 4 * p], target: [0.0, 0.0, 14 + 4 * p], fov: 50 }), uniforms: { uVotiveOn: 0, uMoonCol: [5.5, 6.6, 9.0], uAmb: [0.1, 0.12, 0.18] }, post: (t) => ({ saturation: 0.75 }) }); };
