// s19-slab: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { gothicShot, lightning } from '/song/lib/shots.js';
import { linesIn } from '/song/lib/type.js';
export const kind = 'shader';
export default (P) => { const lines = linesIn(P); return gothicShot(P, { name: 's19-slab', cam: (p, t) => ({ pos: [2.6, 1.2, 4.0 + 3 * p], target: [-3.1, 0.9, 9.2], fov: 42, focus: 6.5 }), uniforms: { uVotive: [-3.1, 0.0, 9.2], uAperG: 0.02 } }); };
