// s20-edge: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { gothicShot, lightning } from '/song/lib/shots.js';
import { linesIn, ease } from '/song/lib/type.js';
export const kind = 'shader';
export default (P) => { const lines = linesIn(P); return gothicShot(P, { name: 's20-edge', cam: (p, t) => ({ pos: [-2.55, 0.95 + 0.05 * p, 8.5 + 0.2 * p], target: [-3.0, 0.82, 9.35], fov: 30, focus: 0.95 }), uniforms: { uVotive: [-3.1, 0.0, 9.2], uAperG: 0.025, uMoonCol: [3.0, 3.6, 5.0] } }); };
