// s23-held: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { spilledShot } from '/song/lib/shots.js';
import { linesIn } from '/song/lib/type.js';
export const kind = 'three';
export default (P) => { const lines = linesIn(P); return spilledShot(P, { name: 's23-held', cam: (p, t) => ({ pos: [0, 6 - 2 * p, -9 + 3 * p], target: [0, 9 - 2 * p, 10], fov: 56 }) }); };
