// s23-held: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { lyricModule, verse, single, shout, note, outFade, ease, clamp01, setLine, lyrics } from '/song/lib/type.js';
export default lyricModule((ctx, t, P, lines) => {
  verse(ctx, t, P, lines, {x: 260, y: 1500, px: 190, align: 'left', group: 2, gap: 1.3});
});
