// s24-trinity: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { spilledShot } from '/song/lib/shots.js';
import { linesIn } from '/song/lib/type.js';
export const kind = 'three';
export default (P) => { const lines = linesIn(P); return spilledShot(P, { name: 's24-trinity', cam: (p, t) => ({ pos: [0, 13 - 0.8 * p, -12 + 0.8 * p], target: [0, 5 + 1.5 * p, 8], fov: 46 }) }); };
