// s24-trinity: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { lyricModule, verse, single, shout, note, outFade, ease, clamp01, setLine, lyrics } from '/song/lib/type.js';
export default lyricModule((ctx, t, P, lines) => {
  verse(ctx, t, P, lines, {x: 1920, y: 1640, px: 210, align: 'center', group: 2, gap: 1.25});
});
