// s29-faith2: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { lyricModule, verse, single, shout, note, outFade, ease, clamp01, setLine, lyrics } from '/song/lib/type.js';
export default lyricModule((ctx, t, P, lines) => {
  shout(ctx, lines[0].words, t, { cx: 1920, y: 1100, big: 400, alpha: outFade(t, P.to - 0.2, P.to) });
  shout(ctx, lines[1].words, t, { cx: 1920, y: 1700, big: 380, alpha: outFade(t, P.to - 0.2, P.to) });
});
