// s29-faith2: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { spilledShot } from '/song/lib/shots.js';
import { linesIn } from '/song/lib/type.js';
export const kind = 'three';
export default (P) => { const lines = linesIn(P); return spilledShot(P, { name: 's29-faith2', cam: (p, t) => ({ pos: [0, 13 - 2 * p, -12 + 3 * p], target: [0, 4 + 3 * p, 8], fov: 56 }), fill: 5.5 }); };
