// s30-fathers2: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { lyricModule, verse, single, shout, note, outFade, ease, clamp01, setLine, lyrics } from '/song/lib/type.js';
export default lyricModule((ctx, t, P, lines) => {
  shout(ctx, lines[0].words, t, { cx: 960, y: 1500, big: 360, alpha: outFade(t, P.to - 0.2, P.to) });
  shout(ctx, lines[1].words, t, { cx: 2900, y: 1500, big: 330, alpha: outFade(t, P.to - 0.2, P.to) });
});
