// s32-holy2: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { spilledShot } from '/song/lib/shots.js';
import { linesIn } from '/song/lib/type.js';
export const kind = 'three';
export default (P) => { const lines = linesIn(P); return spilledShot(P, { name: 's32-holy2', cam: (p, t) => ({ pos: [4.0 * Math.sin(0.6 + 1.2 * p), 9.5, 4 - 4.0 * Math.cos(0.6 + 1.2 * p)], target: [0, 9.5, 4], fov: 60 }), fill: 6.0 }); };
