// s33-mercy: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { spilledShot } from '/song/lib/shots.js';
import { linesIn } from '/song/lib/type.js';
export const kind = 'three';
export default (P) => { const lines = linesIn(P); return spilledShot(P, { name: 's33-mercy', cam: (p, t) => ({ pos: [0, 12.5 - 0.6 * p, -11 + 0.6 * p], target: [0, 6, 8], fov: 44 }), fill: 5.0 }); };
