// s37-end: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { lyricModule, verse, single, shout, note, outFade, ease, clamp01, setLine, lyrics } from '/song/lib/type.js';
export default lyricModule((ctx, t, P, lines) => {
  const tail = lyrics.words.filter((w) => w.start >= P.from - 0.05 && w.start < P.from + 3);
  if (tail.length) setLine(ctx, tail, t, { x: 1920, y: 1800, px: 250, align: 'center', alpha: outFade(t, P.from + 4.2, P.from + 4.8) });
  const k = ease.out3(clamp01((t - P.from - 5.0) / 1.5)) * outFade(t, P.to - 1.6, P.to - 0.4);
  if (k > 0) { note(ctx, 'THE', 1920, 860, { px: 70, align: 'center', alpha: 0.85 * k, track: 0.6 }); shout(ctx, [{ w: 'FAITH', start: P.from + 5.2 }], t, { cx: 1920, y: 1240, big: 360, alpha: k }); note(ctx, 'OF THE APOSTLES', 1920, 1420, { px: 90, align: 'center', alpha: 0.9 * k, track: 0.45, color: '255, 172, 72' }); }
});
