// s37-end: generated by tools/make-scenes.py from the plan in docs/BRIEF.md.
import { spilledShot } from '/song/lib/shots.js';
import { linesIn } from '/song/lib/type.js';
export const kind = 'three';
export default (P) => { const lines = linesIn(P); return spilledShot(P, { name: 's37-end', cam: (p, t) => ({ pos: [0, 13 - 3 * p, -12 + 5 * p], target: [0, 4 + 2 * p, 8], fov: 52 }), fill: 5.0, finish: (t) => ({ fade: Math.min(1, Math.max(0, (t - (P.to - 1.8)) / 1.6)) }) }); };
